name: Docker Build And Deploy

on:
  push:
    branches:
      - prod
      - main
  pull_request:
    branches:
      - prod
      - main

jobs:
  next-build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        env:
          ENV_FILE: ${{ secrets.DISCOVER_ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env
          export CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          export TAG=$([[ $CURRENT_BRANCH == "prod" || $CURRENT_BRANCH == "main" ]] && echo $CURRENT_BRANCH || echo "latest")
          echo "Tag: $TAG"
          export GITHUB_REF_IMAGE=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
          export GITHUB_BRANCH_IMAGE=ghcr.io/$GITHUB_REPOSITORY:$TAG
          export GITHUB_REF_IMAGE=$(echo $GITHUB_REF_IMAGE | tr '[:upper:]' '[:lower:]')
          export GITHUB_BRANCH_IMAGE=$(echo $GITHUB_BRANCH_IMAGE | tr '[:upper:]' '[:lower:]')
          docker build --build-arg version=$GITHUB_SHA -t $GITHUB_REF_IMAGE -t $GITHUB_BRANCH_IMAGE .
          echo "Pushing Images to GitHub Container Registry"
          docker push $GITHUB_REF_IMAGE
          docker push $GITHUB_BRANCH_IMAGE
          rm -f .env

  deploy:
    needs: next-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [prod, main]
    steps:
      - name: Deploy on Server
        if: github.ref == 'refs/heads/${{ matrix.branch }}'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ github.ref == 'refs/heads/prod' && secrets.REMOTE_SERVER_ADDRESS || secrets.DEV_REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.REMOTE_SERVER_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pwd
            cd ~/discover
            sudo docker stop discover || true
            sudo docker rm discover || true
            sudo docker rmi discover || true
            echo ${{ secrets.GHCR_TOKEN }} | sudo docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            sudo docker pull ghcr.io/myriadflow/discover:${{ matrix.branch }}
            sudo docker run --name="discover" -p 9082:3000 -d ghcr.io/myriadflow/discover:${{ matrix.branch }}
