# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Next.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x] # Specify the Node.js versions to test against

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: v18.17.0

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Upload production-ready build artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: nextjs-build
        path: .next

